maintainer       "Copyright 2012, Criteo"
maintainer_email "m.brugidou@criteo.com"
license          "Apache 2.0"
description      "Installs/Configures gitorious"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.1.0"
depends          "rabbitmq"
depends          "passenger_apache2"
depends          "mysql"
depends          "database"
depends          "memcached"
